[general]
import = [
    "~/.config/alacritty/themes/themes/one_dark.toml"
]

[env]
TERM = "alacritty-direct"

[cursor]
style = { shape =  "Block", blinking = "Always" }

[font]
size = 13.0

[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[font.offset]
x = 0
y = 0

[scrolling]
history = 50000

[window]
decorations = "Buttonless"
padding = { x = 15, y = 5 }
dynamic_padding = true
opacity = 0.95 
blur = true 
