import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[cursor]
style = { shape =  "Block", blinking = "Always" }

[colors]
# cursor = { text = "#4c4f69", cursor = "#00ff73" }

[font]
size = 13.0

[font.bold]
# family = "FiraCode Nerd Font"
family = "JetBrainsMono Nerd Font Mono"
style = "Bold"

[font.italic]
# family = "FiraCode Nerd Font"
family = "JetBrainsMono Nerd Font Mono"
style = "Italic"

[font.normal]
# family = "FiraCode Nerd Font"
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[font.offset]
x = 0
y = 0

[scrolling]
history = 50000

[window]
decorations = "Buttonless"
padding = { x = 0, y = 0 }
dynamic_padding = true
opacity = 0.7
blur = true
